name: Node CI Build | App

on:
    pull_request:
        branches: [staging/app]

    workflow_dispatch:

    push:
        branches: [staging/app]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Deployment

        steps:
            - uses: actions/checkout@v2

            - run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm

            - uses: actions/setup-node@v1
              with:
                  node-version: "${{ steps.nvm.outputs.NVMRC }}"

            - run: npm ci
            - run: npx nx lint app
            - run: npx nx test app
            - run: npx nx build app
              env:
                  NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
                  NEXT_PUBLIC_STRAPI_API_KEY: ${{ secrets.NEXT_PUBLIC_STRAPI_API_KEY }}
                  NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}
                  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
                  NEXT_PUBLIC_ALGOLIA_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_API_KEY }}
                  NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
                  NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
                  NEXT_PUBLIC_FACEBOOK_PIXEL: ${{ secrets.NEXT_PUBLIC_FACEBOOK_PIXEL }}
                  ALLOWED_IMAGE_HOSTNAME: ${{ secrets.ALLOWED_IMAGE_HOSTNAME }}
                  NEXT_PUBLIC_MAILCHIMP_SIGNUP_URL: ${{ secrets.NEXT_PUBLIC_MAILCHIMP_SIGNUP_URL }}

            - uses: devmasx/merge-branch@v1.3.1
              with:
                  type: now
                  from_branch: main
                  target_branch: production/app
                  github_token: ${{ secrets.GHP }}
