name: Node CI Build | App

on:
    pull_request:
        branches: [production/app]

    workflow_dispatch:

    push:
        branches: [production/app]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Deployment

        steps:
            - uses: actions/checkout@v2

            - run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm

            - uses: actions/setup-node@v1
              with:
                  node-version: "${{ steps.nvm.outputs.NVMRC }}"

            - run: npm ci
            - run: npx nx lint
            - run: npx nx test
            - run: npx nx build
              env:
                  NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
                  NEXT_PUBLIC_STRAPI_API_KEY: ${{ secrets.NEXT_PUBLIC_STRAPI_API_KEY }}
                  NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}
                  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
                  NEXT_PUBLIC_ALGOLIA_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_API_KEY }}
                  NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
                  NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
                  ALLOWED_IMAGE_HOSTNAME: ${{ secrets.ALLOWED_IMAGE_HOSTNAME }}
