name: Node CI

on:
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm

            - uses: actions/setup-node@v1
              with:
                  node-version: "${{ steps.nvm.outputs.NVMRC }}"

            - run: npm ci
            - run: npx nx run-many --all --target=test
            - run: npx nx export
